[package]
name         = "tuigreet-config"
description  = "Configuration parsing and schema for tuigreet"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
rust-version.workspace = true

[dependencies]
tuigreet-types      = { workspace = true }

chrono              = { workspace = true }
clap                = { workspace = true }
codespan-reporting  = { workspace = true }
dirs                = { workspace = true }
figment             = { workspace = true }
getopts             = { workspace = true }
serde               = { workspace = true }
toml                = { workspace = true }
tracing             = { workspace = true }
